
# Configuration script for SimpleStream Builder

# Define a specific path where build simple streams files.
# By defualt use path '' for expose images.
# prefix: 'images'

# Path of the images.json
images_path: streams/v1

# Normally this field must be with this values for LXC.
datatype: image-downloads

# Define version of the products.
format: "products:1.0"

# Define list of products
products:

  # Sabayon Builder rootfs
  - name: sabayon-builder:current:amd64:default
    arch: amd64
    release: current
    os: Sabayon
    release_title: "Sabayon Builder"
    directory: sbi/sabayon-builder
    # Path where retrieve images informations and files.
    # This option is used by build-images-file.
    # If it is used the directory directly from source-dir
    # this option is not needed.
    #prefix_path: "http://my.mottainai.org/namespace/lxd-sabayon-builder"

    days: 1
    aliases:
      - "sabayon/builder"

  # Sabayon Base rootfs
  - name: sabayon-base:current:amd64:default
    arch: amd64
    release: current
    os: Sabayon
    directory: sbi/sabayon-base
    # Currently distrobuilder doesn't implement a generator for inject
    # files from host before enter on chroot. In additional, for
    # oraclelinux it seems that .distrobuilder is not cleaned correctly.
    # If it's defined a script then instead of call build-lxc and build-lxc
    # I split creation in two steps: build-dir + script + pack-lxc|pack-lxd
    # build_script_hook: "/myscript.sh"
    #hidden: true
    # Define number of images maintains for the product. Default is 1 day/image.
    #days: 1
    aliases:
      - "sabayon/base"

