on: push
concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
name: Build on push
jobs:
  tests-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18.x", "1.19.x", "1.20.x"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deps
        run: |
            sudo -E env "PATH=$PATH" make deps

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: Build test
        run: sudo -E env "PATH=$PATH" make goreleaser-snapshot

      #      - name: Tests
      #  run: |
      #    sudo -E env "PATH=$PATH" make test-coverage
